export {
  metricsRegistry,
  startDefaultProcessMetrics,
  getProcessServiceLabel,
  renderPrometheusMetrics,
  prometheusContentType,
} from "./registry.js";

export {
  DURATION_BUCKETS_SECONDS,
  observeDuration,
  observeDurationLabeled,
  createMusicMetrics,
  getMusicMetrics,
  resetMusicMetricsForTests,
  incCallback,
  observeCallbackPhase,
  recordGenerationTransition,
  sanitizeErrorCode,
  musicGenerationStartedTotal,
  musicGenerationCompletedTotal,
  musicGenerationFailedTotal,
  musicCallbackTotal,
  musicPersistSuccessTotal,
  musicPersistFailedTotal,
  musicPersistRetryTotal,
  musicAudioNotReadyTotal,
  musicStorageNotFoundTotal,
  musicStorageTransientErrorTotal,
  musicProviderSubmitAttemptsTotal,
  recordProviderSubmitAttempt,
  musicCallbackDurationSeconds,
  musicCallbackPhaseDurationSeconds,
  musicProviderSubmitDurationSeconds,
  musicProviderPollDurationSeconds,
  musicDownloadDurationSeconds,
  musicUploadDurationSeconds,
  musicPersistDurationSeconds,
  musicStoragePutDurationSeconds,
  musicStorageGetDurationSeconds,
  musicGenerationQueueDepth,
  musicPersistenceQueueDepth,
  type CallbackOutcome,
  type CallbackPhase,
  type AudioNotReadyReason,
  type StorageOp,
  type MetricErrorCode,
  type ProviderSubmitAttemptResult,
  type MusicMetrics,
} from "./metrics.js";

export {
  createMurekaMetrics,
  getMurekaMetrics,
  murekaVocalCloneStartedTotal,
  murekaVocalCloneCompletedTotal,
  murekaVocalCloneFailedTotal,
  murekaGenerationStartedTotal,
  murekaGenerationCompletedTotal,
  murekaGenerationPartialTotal,
  murekaGenerationFailedTotal,
  murekaPollTotal,
  murekaProviderErrorTotal,
  murekaSubmitUnknownTotal,
  murekaRefundTotal,
  murekaEstimatedCostUsdTotal,
  murekaActiveGenerationTasks,
  murekaQueueDepth,
  murekaR2PersistenceFailedTotal,
  murekaGenerationDurationSeconds,
  type MurekaMetrics,
} from "./mureka-metrics.js";

export {
  handleMetricsHttpRequest,
  startMetricsHttpServer,
  type MetricsHttpAuth,
  type StartMetricsHttpServerOptions,
} from "./http-handler.js";

export { createInstrumentedObjectStorage } from "./instrumented-object-storage.js";

export {
  createVoiceDeletionMetrics,
  getVoiceDeletionMetrics,
  resetVoiceDeletionMetricsForTests,
  voiceDeletionRequestedTotal,
  voiceDeletionLocalPurgeCompletedTotal,
  voiceDeletionPendingProviderTotal,
  voiceDeletionConfirmedTotal,
  voiceDeletionFailedTotal,
  voiceDeletionPendingProviderGauge,
  voiceDeletionOldestPendingSeconds,
  type VoiceDeletionMetrics,
} from "./voice-deletion-metrics.js";
